apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dgraphs.thoth-station.ninja
spec:
  group: thoth-station.ninja
  names:
    kind: Dgraph
    listKind: DgraphList
    plural: dgraphs
    singular: dgraph
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
